
-- Usagers

INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U001', 'Marissa', 'Kaup', 'mkaup@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U002', 'Tyesha', 'Suniga', 'tsuniga@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U003', 'Valorie', 'Lampron', 'vlampron@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U004', 'Linda', 'Tai', 'ltai@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U005', 'Louetta', 'Nogueira', 'lnogueira@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U006', 'Maudie', 'Leto', 'mleto@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U007', 'America', 'Hower', 'ahower@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U008', 'Neely', 'Addis', 'naddis@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U009', 'Marin', 'Honig', 'mhonig@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U010', 'Herb', 'Jennette', 'hjennette@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U011', 'Loren', 'Fail', 'lfail@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U012', 'Danyel', 'Himes', 'fhimes@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U013', 'Tommie', 'Imboden', 'timboden@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U014', 'Lorene', 'Koenen', 'lkoenen@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U015', 'Sabra', 'Pricer', 'spricer@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U016', 'Shawnda', 'Houchens', 'shouchens@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U017', 'Dulce', 'Wardlaw', 'dwardlaw@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U018', 'Deandre', 'Stupka', 'dstupka@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U019', 'Lon', 'Kral', 'lkral@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U020', 'Billye', 'Marcelino', 'bmarcelino@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U021', 'Emilie', 'Jones', 'ejones@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U022', 'John', 'Smith', 'jsmith@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U023', 'Mary', 'Smith', 'msmith@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U024', 'Tommie', 'Imboden', 'timboden@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U025', 'Lorene', 'Koenen', 'lkoenen@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U026', 'Sabra', 'Pricer', 'spricer@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U027', 'Shawnda', 'Houchens', 'shouchens@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U028', 'Dulce', 'Wardlaw', 'dwardlaw@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U029', 'Deandre', 'Stupka', 'dstupka@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U030', 'Lon', 'Kral', 'lkral@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U031', 'Herb', 'Jennette', 'hjennette@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U032', 'Daren', 'Smith', 'dsmith@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U033', 'Danyel', 'Himes', 'fhimes@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U034', 'Tommie', 'Imboden', 'timboden@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U035', 'Lorene', 'Koenen', 'lkoenen@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U036', 'Sabra', 'Pricer', 'spricer@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U037', 'Shawnda', 'Houchens', 'shouchens@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U038', 'Dulce', 'Wardlaw', 'dwardlaw@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U039', 'Deandre', 'Stupka', 'dstupka@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Usager VALUES('U040', 'Lon', 'Kral', 'lkral@gmail.com');

-- Employés

-- Gestionnaires

INSERT INTO TOURNOIS_SPORTSDB.Employe VALUES('EMP1', 'Stanton', 'Marlow', 'Gestionnaire');
INSERT INTO TOURNOIS_SPORTSDB.Gestionnaire VALUES('EMP1', '(705) 471-8331', 'swarlow@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Employe VALUES('EMP2', 'Romaine', 'Delany', 'Gestionnaire');
INSERT INTO TOURNOIS_SPORTSDB.Gestionnaire VALUES('EMP2', '(705) 471-8331', 'rdelany@gmail.com');
INSERT INTO TOURNOIS_SPORTSDB.Employe VALUES('EMP3', 'Laine', 'Zeiger', 'Gestionnaire');
INSERT INTO TOURNOIS_SPORTSDB.Gestionnaire VALUES('EMP3', '(705) 471-8331', 'lzeiger@gmail.com');

-- Arbitres

INSERT INTO TOURNOIS_SPORTSDB.Employe VALUES('EMP4', 'Adam', 'Markham', 'Arbitre');
INSERT INTO TOURNOIS_SPORTSDB.Arbitre VALUES('EMP4', 3);
INSERT INTO TOURNOIS_SPORTSDB.Employe VALUES('EMP5', 'Heidy', 'Hellums', 'Arbitre');
INSERT INTO TOURNOIS_SPORTSDB.Arbitre VALUES('EMP5', 3);
INSERT INTO TOURNOIS_SPORTSDB.Employe VALUES('EMP6', 'Audry', 'Romaine', 'Arbitre');
INSERT INTO TOURNOIS_SPORTSDB.Arbitre VALUES('EMP6', 3);

-- Sports

INSERT INTO TOURNOIS_SPORTSDB.Sport VALUES('SP01', 'Soccer', 'Botter le ballon dans le fillet.', 7, 11);
INSERT INTO TOURNOIS_SPORTSDB.Sport VALUES('SP02', 'Basketball', 'Lancer le ballon dans le panier.', 5, 10);

-- Ligues

INSERT INTO TOURNOIS_SPORTSDB.Ligue VALUES('L007', 'SP01', 'C');
INSERT INTO TOURNOIS_SPORTSDB.Ligue VALUES('L022', 'SP02', 'R');
INSERT INTO TOURNOIS_SPORTSDB.Ligue VALUES('L040', 'SP02', 'C');

-- Ligue L007

-- Equipe 1

INSERT INTO TOURNOIS_SPORTSDB.Gerant VALUES('U001', 'Diplomes de Soccer et de Basketball');
INSERT INTO TOURNOIS_SPORTSDB.Equipe VALUES('EQU1', 'Titans', FALSE, 'U001', 'L007');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U001', 'EQU1');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U002', 'EQU1');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U003', 'EQU1');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U004', 'EQU1');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U005', 'EQU1');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U006', 'EQU1');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U007', 'EQU1');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U008', 'EQU1');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U009', 'EQU1');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U010', 'EQU1');

-- Équipe 2

INSERT INTO TOURNOIS_SPORTSDB.Gerant VALUES('U011', 'Diplome de Soccer');
INSERT INTO TOURNOIS_SPORTSDB.Equipe VALUES('EQU2', 'Lions', FALSE, 'U011', 'L007');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U011', 'EQU2');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U012', 'EQU2');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U013', 'EQU2');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U014', 'EQU2');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U015', 'EQU2');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U016', 'EQU2');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U017', 'EQU2');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U018', 'EQU2');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U019', 'EQU2');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U020', 'EQU2');

-- Équipe 3

INSERT INTO TOURNOIS_SPORTSDB.Gerant VALUES('U021', 'Diplome de Basketball');
INSERT INTO TOURNOIS_SPORTSDB.Equipe VALUES('EQU3', 'Fonceurs', FALSE, 'U021', 'L007');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U021', 'EQU3');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U022', 'EQU3');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U023', 'EQU3');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U024', 'EQU3');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U025', 'EQU3');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U026', 'EQU3');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U027', 'EQU3');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U028', 'EQU3');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U029', 'EQU3');
INSERT INTO TOURNOIS_SPORTSDB.UsagerEquipe VALUES('U030', 'EQU3');

-- Ligue L022

-- Equipe 1

INSERT INTO TOURNOIS_SPORTSDB.Equipe VALUES('EQU4', 'Titans', FALSE, 'U001', 'L022');

-- Équipe 2

INSERT INTO TOURNOIS_SPORTSDB.Equipe VALUES('EQU5', 'Lions', FALSE, 'U011', 'L022');

-- Équipe 3

INSERT INTO TOURNOIS_SPORTSDB.Equipe VALUES('EQU6', 'Fonceurs', FALSE, 'U021', 'L022');

-- Ligue L040

-- Equipe 1

INSERT INTO TOURNOIS_SPORTSDB.Equipe VALUES('EQU7', 'Titans', FALSE, 'U001', 'L040');

-- Équipe 2

INSERT INTO TOURNOIS_SPORTSDB.Equipe VALUES('EQU8', 'Lions', FALSE, 'U011', 'L040');

-- Équipe 3

INSERT INTO TOURNOIS_SPORTSDB.Equipe VALUES('EQU9', 'Fonceurs', FALSE, 'U021', 'L040');

-- Usagers sport

INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U001', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U002', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U003', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U004', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U005', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U006', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U007', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U008', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U009', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U010', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U011', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U012', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U013', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U014', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U015', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U016', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U017', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U018', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U019', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U020', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U021', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U022', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U023', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U024', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U025', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U026', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U027', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U028', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U029', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U030', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U031', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U032', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U033', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U034', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U035', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U036', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U037', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U038', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U039', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U040', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U001', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U002', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U003', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U004', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U005', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U006', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U007', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U008', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U009', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U010', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U011', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U012', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U013', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U014', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U015', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U016', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U017', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U018', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U019', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U020', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U021', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U022', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U023', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U024', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U025', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U026', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U027', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U028', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U029', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U030', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U031', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U032', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U033', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U034', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U035', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U036', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U037', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U038', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U039', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.UsagerSport VALUES('U040', 'SP02');

-- Saisons

-- Saison 1

INSERT INTO TOURNOIS_SPORTSDB.Saison VALUES('S001', 'L007', (to_date('2016-05-05', 'YYYY-MM-DD')), (to_date('2016-05-12', 'YYYY-MM-DD')), (to_date('2016-08-15', 'YYYY-MM-DD')), 3);

INSERT INTO TOURNOIS_SPORTSDB.Match VALUES('M001', (to_date('2016-05-13', 'YYYY-MM-DD')), '13:00', 'Sportmax, Ottawa');
INSERT INTO TOURNOIS_SPORTSDB.Match VALUES('M002', (to_date('2016-06-30', 'YYYY-MM-DD')), '17:00', 'Sportmax, Ottawa');
INSERT INTO TOURNOIS_SPORTSDB.Match VALUES('M003', (to_date('2016-08-15', 'YYYY-MM-DD')), '20:00', 'Minto, Ottawa');

INSERT INTO TOURNOIS_SPORTSDB.MatchSaison VALUES('M001', 'S001');
INSERT INTO TOURNOIS_SPORTSDB.MatchSaison VALUES('M002', 'S001');
INSERT INTO TOURNOIS_SPORTSDB.MatchSaison VALUES('M003', 'S001');

INSERT INTO TOURNOIS_SPORTSDB.EquipeSaison VALUES('EQU1', 'S001');
INSERT INTO TOURNOIS_SPORTSDB.EquipeSaison VALUES('EQU2', 'S001');
INSERT INTO TOURNOIS_SPORTSDB.EquipeSaison VALUES('EQU3', 'S001');

INSERT INTO TOURNOIS_SPORTSDB.Paiement VALUES('U001', 'EQU1', 'S001', (to_date('2016-05-03', 'YYYY-MM-DD')), 4424);
INSERT INTO TOURNOIS_SPORTSDB.Paiement VALUES('U011', 'EQU2', 'S001', (to_date('2016-05-02', 'YYYY-MM-DD')), 5327);
INSERT INTO TOURNOIS_SPORTSDB.Paiement VALUES('U021', 'EQU3', 'S001', (to_date('2016-05-01', 'YYYY-MM-DD')), 9089);

INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU1', 'M001', 4);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU2', 'M001', 3);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU1', 'M002', 5);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU3', 'M002', 2);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU2', 'M003', 2);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU3', 'M003', 1);

-- Saison 2

INSERT INTO TOURNOIS_SPORTSDB.Saison VALUES('S002', 'L022', (to_date('2016-01-05', 'YYYY-MM-DD')), (to_date('2016-01-12', 'YYYY-MM-DD')), (to_date('2016-04-15', 'YYYY-MM-DD')), 3);

INSERT INTO TOURNOIS_SPORTSDB.Match VALUES('M004', (to_date('2016-01-14', 'YYYY-MM-DD')), '13:00', 'Sportmax, Ottawa');
INSERT INTO TOURNOIS_SPORTSDB.Match VALUES('M005', (to_date('2016-03-14', 'YYYY-MM-DD')), '14:00', 'Sportmax, Ottawa');
INSERT INTO TOURNOIS_SPORTSDB.Match VALUES('M006', (to_date('2016-03-14', 'YYYY-MM-DD')), '18:00', 'Lees, Ottawa');

INSERT INTO TOURNOIS_SPORTSDB.MatchSaison VALUES('M004', 'S002');
INSERT INTO TOURNOIS_SPORTSDB.MatchSaison VALUES('M005', 'S002');
INSERT INTO TOURNOIS_SPORTSDB.MatchSaison VALUES('M006', 'S002');

INSERT INTO TOURNOIS_SPORTSDB.EquipeSaison VALUES('EQU4', 'S002');
INSERT INTO TOURNOIS_SPORTSDB.EquipeSaison VALUES('EQU5', 'S002');
INSERT INTO TOURNOIS_SPORTSDB.EquipeSaison VALUES('EQU6', 'S002');

INSERT INTO TOURNOIS_SPORTSDB.Paiement VALUES('U001', 'EQU4', 'S002', (to_date('2016-01-03', 'YYYY-MM-DD')), 4424);
INSERT INTO TOURNOIS_SPORTSDB.Paiement VALUES('U011', 'EQU5', 'S002', (to_date('2016-01-02', 'YYYY-MM-DD')), 5327);
INSERT INTO TOURNOIS_SPORTSDB.Paiement VALUES('U021', 'EQU6', 'S002', (to_date('2016-01-01', 'YYYY-MM-DD')), 9089);

INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU4', 'M004', 2);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU5', 'M004', 1);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU4', 'M005', 1);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU6', 'M005', 4);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU5', 'M006', 4);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU6', 'M006', 3);

-- Saison 3

INSERT INTO TOURNOIS_SPORTSDB.Saison VALUES('S003', 'L040', (to_date('2016-01-05', 'YYYY-MM-DD')), (to_date('2016-01-12', 'YYYY-MM-DD')), (to_date('2016-04-15', 'YYYY-MM-DD')), 10);

INSERT INTO TOURNOIS_SPORTSDB.Match VALUES('M007', (to_date('2016-01-14', 'YYYY-MM-DD')), '13:00', 'Minto, Ottawa');
INSERT INTO TOURNOIS_SPORTSDB.Match VALUES('M008', (to_date('2016-03-14', 'YYYY-MM-DD')), '14:00', 'Lees, Ottawa');
INSERT INTO TOURNOIS_SPORTSDB.Match VALUES('M009', (to_date('2016-04-15', 'YYYY-MM-DD')), '20:00', 'Sportmax, Ottawa');

INSERT INTO TOURNOIS_SPORTSDB.MatchSaison VALUES('M007', 'S003');
INSERT INTO TOURNOIS_SPORTSDB.MatchSaison VALUES('M008', 'S003');
INSERT INTO TOURNOIS_SPORTSDB.MatchSaison VALUES('M009', 'S003');

INSERT INTO TOURNOIS_SPORTSDB.EquipeSaison VALUES('EQU7', 'S003');
INSERT INTO TOURNOIS_SPORTSDB.EquipeSaison VALUES('EQU8', 'S003');
INSERT INTO TOURNOIS_SPORTSDB.EquipeSaison VALUES('EQU9', 'S003');

INSERT INTO TOURNOIS_SPORTSDB.Paiement VALUES('U001', 'EQU7', 'S003', (to_date('2016-01-03', 'YYYY-MM-DD')), 4424);
INSERT INTO TOURNOIS_SPORTSDB.Paiement VALUES('U011', 'EQU8', 'S003', (to_date('2016-01-02', 'YYYY-MM-DD')), 5327);
INSERT INTO TOURNOIS_SPORTSDB.Paiement VALUES('U021', 'EQU9', 'S003', (to_date('2016-01-01', 'YYYY-MM-DD')), 9089);

INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU7', 'M007', 4);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU8', 'M007', 3);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU7', 'M008', 4);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU9', 'M008', 2);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU8', 'M009', 4);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU9', 'M009', 1);

-- Gestionnaires de ligue

INSERT INTO TOURNOIS_SPORTSDB.GestionnaireLigue VALUES('EMP1', 'L007');
INSERT INTO TOURNOIS_SPORTSDB.GestionnaireLigue VALUES('EMP2', 'L022');
INSERT INTO TOURNOIS_SPORTSDB.GestionnaireLigue VALUES('EMP3', 'L040');

-- Arbitres de ligue

INSERT INTO TOURNOIS_SPORTSDB.ArbitreLigue VALUES('EMP4', 'L007');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreLigue VALUES('EMP5', 'L022');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreLigue VALUES('EMP6', 'L040');

-- Arbitre sports

INSERT INTO TOURNOIS_SPORTSDB.ArbitreSport VALUES('EMP4', 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreSport VALUES('EMP5', 'SP02');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreSport VALUES('EMP6', 'SP02');

-- Arbitre matchs

INSERT INTO TOURNOIS_SPORTSDB.ArbitreMatch VALUES('EMP4', 'M001');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreMatch VALUES('EMP4', 'M002');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreMatch VALUES('EMP4', 'M003');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreMatch VALUES('EMP5', 'M004');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreMatch VALUES('EMP5', 'M005');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreMatch VALUES('EMP5', 'M006');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreMatch VALUES('EMP6', 'M007');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreMatch VALUES('EMP6', 'M008');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreMatch VALUES('EMP6', 'M009');

-- Tournois

INSERT INTO TOURNOIS_SPORTSDB.Tournoi VALUES('T110', 'Diabetes', 0.00, (to_date('2016-05-01', 'YYYY-MM-DD')), (to_date('2016-06-01', 'YYYY-MM-DD')), 'SP01');
INSERT INTO TOURNOIS_SPORTSDB.Tournoi VALUES('T001', 'Cancer', 0.00, (to_date('2016-07-01', 'YYYY-MM-DD')), (to_date('2016-08-01', 'YYYY-MM-DD')), 'SP02');


-- Commanditaire pour tournoi

INSERT INTO TOURNOIS_SPORTSDB.Commanditaire VALUES('C001', 'Ballons Inc.', '(613) 252-9589');
INSERT INTO TOURNOIS_SPORTSDB.Commanditaire VALUES('C002', 'Redbull', '(613) 434-5353');
INSERT INTO TOURNOIS_SPORTSDB.CommanditaireTournoi VALUES ('C001', 'T110', 1000.00);
INSERT INTO TOURNOIS_SPORTSDB.CommanditaireTournoi VALUES ('C002', 'T001', 2000.00);

-- Matchs

INSERT INTO TOURNOIS_SPORTSDB.Match VALUES('M010', (to_date('2017-01-14', 'YYYY-MM-DD')), '13:00', 'Sportmax, Ottawa');
INSERT INTO TOURNOIS_SPORTSDB.Match VALUES('M011', (to_date('2017-03-14', 'YYYY-MM-DD')), '14:00', 'Sportmax, Ottawa');
INSERT INTO TOURNOIS_SPORTSDB.Match VALUES('M012', (to_date('2017-03-14', 'YYYY-MM-DD')), '18:00', 'Lees, Ottawa');

INSERT INTO TOURNOIS_SPORTSDB.MatchTournoi VALUES('M010', 'T110');
INSERT INTO TOURNOIS_SPORTSDB.MatchTournoi VALUES('M011', 'T110');
INSERT INTO TOURNOIS_SPORTSDB.MatchTournoi VALUES('M012', 'T110');

INSERT INTO TOURNOIS_SPORTSDB.EquipeTournoi VALUES('EQU1', 'T110', 100.00);
INSERT INTO TOURNOIS_SPORTSDB.EquipeTournoi VALUES('EQU2', 'T110', 100.00);
INSERT INTO TOURNOIS_SPORTSDB.EquipeTournoi VALUES('EQU3', 'T110', 100.00);

INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU1', 'M010', 4);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU2', 'M010', 3);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU1', 'M011', 4);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU3', 'M011', 2);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU2', 'M012', 4);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU3', 'M012', 1);

INSERT INTO TOURNOIS_SPORTSDB.Match VALUES('M013', (to_date('2017-01-14', 'YYYY-MM-DD')), '13:00', 'Sportmax, Ottawa');
INSERT INTO TOURNOIS_SPORTSDB.Match VALUES('M014', (to_date('2017-03-14', 'YYYY-MM-DD')), '14:00', 'Sportmax, Ottawa');
INSERT INTO TOURNOIS_SPORTSDB.Match VALUES('M015', (to_date('2017-03-14', 'YYYY-MM-DD')), '18:00', 'Lees, Ottawa');

INSERT INTO TOURNOIS_SPORTSDB.MatchTournoi VALUES('M013', 'T001');
INSERT INTO TOURNOIS_SPORTSDB.MatchTournoi VALUES('M014', 'T001');
INSERT INTO TOURNOIS_SPORTSDB.MatchTournoi VALUES('M015', 'T001');

INSERT INTO TOURNOIS_SPORTSDB.EquipeTournoi VALUES('EQU1', 'T001', 100.00);
INSERT INTO TOURNOIS_SPORTSDB.EquipeTournoi VALUES('EQU2', 'T001', 100.00);
INSERT INTO TOURNOIS_SPORTSDB.EquipeTournoi VALUES('EQU3', 'T001', 100.00);

INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU1', 'M013', 3);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU2', 'M013', 6);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU1', 'M014', 2);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU3', 'M014', 3);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU2', 'M015', 4);
INSERT INTO TOURNOIS_SPORTSDB.EquipeMatch VALUES('EQU3', 'M015', 3);

INSERT INTO TOURNOIS_SPORTSDB.ArbitreMatch VALUES('EMP4', 'M010');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreMatch VALUES('EMP4', 'M011');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreMatch VALUES('EMP4', 'M012');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreMatch VALUES('EMP5', 'M013');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreMatch VALUES('EMP5', 'M014');
INSERT INTO TOURNOIS_SPORTSDB.ArbitreMatch VALUES('EMP5', 'M015');

